from fastapi import APIRouter

from app.api.v1 import (
    approvals,
    attachments,
    audit,
    auth,
    closing,
    compliance,
    dues,
    finance,
    gst,
    health,
    inventory,
    invoices,
    items,
    locations,
    opening,
    parties,
    payments,
    purchases,
    rates,
    receivables,
    reports,
    returns,
    schemes,
    settings,
    stock,
    stock_ops,
    system,
    tally,
    transport,
    users,
)

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(locations.router)
api_router.include_router(settings.router)
api_router.include_router(audit.router)
api_router.include_router(items.router)
api_router.include_router(parties.router)
api_router.include_router(opening.router)
api_router.include_router(stock.router)
api_router.include_router(dues.router)
api_router.include_router(receivables.router)
api_router.include_router(finance.router)
api_router.include_router(purchases.router)
api_router.include_router(stock_ops.router)
api_router.include_router(rates.router)
api_router.include_router(inventory.router)
api_router.include_router(invoices.router)
api_router.include_router(payments.router)
api_router.include_router(approvals.router)
api_router.include_router(returns.credit_router)
api_router.include_router(returns.debit_router)
api_router.include_router(transport.router)
api_router.include_router(compliance.router)
api_router.include_router(attachments.router)
api_router.include_router(schemes.router)
api_router.include_router(closing.router)
api_router.include_router(reports.router)
api_router.include_router(gst.router)
api_router.include_router(system.router)
api_router.include_router(tally.router)
