"""inventory analytics and write downs

Revision ID: 0020
Revises: 0019
Create Date: 2026-10-10 03:00:37.991772+00:00

FM6 (docs/FINANCE_REVIEW.md F10-F14): stock write-down documents (value-only, to net realisable
value), lead time and safety days on items and suppliers, and the replenishment and NRV
settings. Hand edits: the stock ledger gains the ref type 'stock_writedown' and the number
series 'stock_writedown' (Alembic does not diff CHECKs, so both are widened and narrowed again
on downgrade); write-downs get the issued-document triggers of migration 0014. Downgrading
removes the write-down ledger rows, which only a database restore could bring back.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "0020"
down_revision: str | None = "0019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


STOCK_REF_OLD = (
    "ref_type IN ('opening', 'purchase', 'purchase_return', 'sale', 'sale_return', "
    "'transfer', 'adjustment', 'stock_adjustment')"
)
STOCK_REF_NEW = (
    "ref_type IN ('opening', 'purchase', 'purchase_return', 'sale', 'sale_return', "
    "'transfer', 'adjustment', 'stock_adjustment', 'stock_writedown')"
)
DOC_TYPE_OLD = (
    "doc_type IN ('sales_invoice', 'credit_note', 'debit_note', 'delivery_challan', "
    "'purchase_entry', 'payment_receipt', 'cash_voucher', 'stock_adjustment', "
    "'bad_debt_writeoff')"
)
DOC_TYPE_NEW = (
    "doc_type IN ('sales_invoice', 'credit_note', 'debit_note', 'delivery_challan', "
    "'purchase_entry', 'payment_receipt', 'cash_voucher', 'stock_adjustment', "
    "'bad_debt_writeoff', 'stock_writedown')"
)
ISSUED = ("stock_writedown", "stock_writedown_line")


def _swap_check(name: str, table: str, condition: str) -> None:
    op.drop_constraint(op.f(name), table, type_="check")
    op.create_check_constraint(op.f(name), table, condition)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_writedown",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("writedown_date", sa.Date(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_stock_writedown_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_writedown")),
        sa.UniqueConstraint(
            "tenant_id", "number", name=op.f("uq_stock_writedown_tenant_id_number")
        ),
    )
    op.create_table(
        "stock_writedown_line",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("writedown_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("old_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("new_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("market_rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_writedown_line_positive_qty")),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_stock_writedown_line_item_id_item"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["writedown_id"],
            ["stock_writedown.id"],
            name=op.f("fk_stock_writedown_line_writedown_id_stock_writedown"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_writedown_line")),
    )
    op.add_column("item", sa.Column("lead_time_days", sa.Integer(), nullable=True))
    op.add_column("item", sa.Column("safety_days", sa.Integer(), nullable=True))
    op.add_column("party", sa.Column("lead_time_days", sa.Integer(), nullable=True))
    op.add_column(
        "shop_settings",
        sa.Column("default_lead_time_days", sa.Integer(), server_default="7", nullable=False),
    )
    op.add_column(
        "shop_settings",
        sa.Column("default_safety_days", sa.Integer(), server_default="2", nullable=False),
    )
    op.add_column(
        "shop_settings",
        sa.Column("fsn_fast_min_days", sa.Integer(), server_default="15", nullable=False),
    )
    op.add_column(
        "shop_settings",
        sa.Column(
            "nrv_selling_cost_pct",
            sa.Numeric(precision=5, scale=2),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "shop_settings",
        sa.Column("nrv_writedown_enabled", sa.Boolean(), server_default="true", nullable=False),
    )
    _swap_check("ck_stock_ledger_stock_ref", "stock_ledger", STOCK_REF_NEW)
    _swap_check("ck_document_sequence_doc_type", "document_sequence", DOC_TYPE_NEW)
    # Write-downs are issued documents (ADR 0010): never deleted, figures never edited.
    for table in ISSUED:
        op.execute(
            f"CREATE TRIGGER {table}_no_delete BEFORE DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_issued_delete()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_edit BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_issued_edit()"
        )


def downgrade() -> None:
    for table in ISSUED:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_edit ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_delete ON {table}")
    # The ledger is append-only; its guard is lifted for this one removal.
    op.execute("ALTER TABLE stock_ledger DISABLE TRIGGER USER")
    op.execute("DELETE FROM stock_ledger WHERE ref_type = 'stock_writedown'")
    op.execute("ALTER TABLE stock_ledger ENABLE TRIGGER USER")
    op.execute("DELETE FROM document_sequence WHERE doc_type = 'stock_writedown'")
    _swap_check("ck_document_sequence_doc_type", "document_sequence", DOC_TYPE_OLD)
    _swap_check("ck_stock_ledger_stock_ref", "stock_ledger", STOCK_REF_OLD)
    op.drop_column("shop_settings", "nrv_writedown_enabled")
    op.drop_column("shop_settings", "nrv_selling_cost_pct")
    op.drop_column("shop_settings", "fsn_fast_min_days")
    op.drop_column("shop_settings", "default_safety_days")
    op.drop_column("shop_settings", "default_lead_time_days")
    op.drop_column("party", "lead_time_days")
    op.drop_column("item", "safety_days")
    op.drop_column("item", "lead_time_days")
    op.drop_table("stock_writedown_line")
    op.drop_table("stock_writedown")
