"""vehicles trips and drop ship links

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-09 18:08:43.660643+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("owner_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("is_own", sa.Boolean(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["party_id"], ["party.id"], name=op.f("fk_vehicle_party_id_party"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_vehicle_tenant_id_number")),
    )
    op.create_table(
        "trip",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trip_date", sa.Date(), nullable=False),
        sa.Column("vehicle_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=True),
        sa.Column("purchase_id", sa.Integer(), nullable=True),
        sa.Column("from_place", sa.String(length=150), nullable=False),
        sa.Column("to_place", sa.String(length=150), nullable=False),
        sa.Column("freight_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.CheckConstraint("freight_amount >= 0", name=op.f("ck_trip_freight_not_negative")),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["sales_invoice.id"],
            name=op.f("fk_trip_invoice_id_sales_invoice"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_trip_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchase.id"],
            name=op.f("fk_trip_purchase_id_purchase"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicle.id"],
            name=op.f("fk_trip_vehicle_id_vehicle"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trip")),
    )
    op.create_index("ix_trip_date", "trip", ["trip_date"], unique=False)
    op.create_index("ix_trip_invoice", "trip", ["invoice_id"], unique=False)
    op.create_table(
        "drop_ship_link",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sales_line_id", sa.Integer(), nullable=False),
        sa.Column("purchase_line_id", sa.Integer(), nullable=False),
        sa.Column("base_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.CheckConstraint("base_qty > 0", name=op.f("ck_drop_ship_link_positive_qty")),
        sa.ForeignKeyConstraint(
            ["purchase_line_id"],
            ["purchase_line.id"],
            name=op.f("fk_drop_ship_link_purchase_line_id_purchase_line"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sales_line_id"],
            ["sales_line.id"],
            name=op.f("fk_drop_ship_link_sales_line_id_sales_line"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drop_ship_link")),
        sa.UniqueConstraint("sales_line_id", name=op.f("uq_drop_ship_link_sales_line_id")),
    )
    op.create_index(
        "ix_drop_ship_link_purchase_line", "drop_ship_link", ["purchase_line_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_drop_ship_link_purchase_line", table_name="drop_ship_link")
    op.drop_table("drop_ship_link")
    op.drop_index("ix_trip_invoice", table_name="trip")
    op.drop_index("ix_trip_date", table_name="trip")
    op.drop_table("trip")
    op.drop_table("vehicle")
    # ### end Alembic commands ###
