"""credit and debit notes

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-09 17:58:12.274304+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


APPROVAL_OLD = "action IN ('credit_override', 'below_cost', 'discount', 'backdate')"
APPROVAL_NEW = (
    "action IN ('credit_override', 'below_cost', 'discount', 'backdate', 'late_return')"
)


def upgrade() -> None:
    # A new approval action: Alembic does not diff CHECK constraints, so change it by hand.
    op.drop_constraint(op.f("ck_approval_approval_action"), "approval", type_="check")
    op.create_check_constraint(op.f("ck_approval_approval_action"), "approval", APPROVAL_NEW)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "debit_note",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(length=16), nullable=False),
        sa.Column("financial_year", sa.String(length=5), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("purchase_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("note_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column(
            "supply_kind",
            sa.Enum(
                "intra_state",
                "inter_state",
                name="supply_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("taxable_value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cgst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("sgst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("igst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("round_off", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_debit_note_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party.id"],
            name=op.f("fk_debit_note_party_id_party"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchase.id"],
            name=op.f("fk_debit_note_purchase_id_purchase"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_debit_note")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_debit_note_tenant_id_number")),
    )
    op.create_index("ix_debit_note_purchase", "debit_note", ["purchase_id"], unique=False)
    op.create_table(
        "credit_note",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(length=16), nullable=False),
        sa.Column("financial_year", sa.String(length=5), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("note_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("bill_to_name", sa.String(length=150), nullable=False),
        sa.Column("bill_to_address", sa.Text(), nullable=False),
        sa.Column("bill_to_gstin", sa.String(length=15), nullable=True),
        sa.Column("place_of_supply", sa.String(length=2), nullable=False),
        sa.Column(
            "supply_kind",
            sa.Enum(
                "intra_state",
                "inter_state",
                name="supply_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "supply_type",
            sa.Enum(
                "B2B",
                "B2C",
                name="supply_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("taxable_value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cgst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("sgst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("igst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("round_off", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("approved_by", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["sales_invoice.id"],
            name=op.f("fk_credit_note_invoice_id_sales_invoice"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_credit_note_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party.id"],
            name=op.f("fk_credit_note_party_id_party"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["site.id"], name=op.f("fk_credit_note_site_id_site"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_note")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_credit_note_tenant_id_number")),
    )
    op.create_index("ix_credit_note_invoice", "credit_note", ["invoice_id"], unique=False)
    op.create_table(
        "debit_note_line",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("debit_note_id", sa.Integer(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("purchase_line_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=150), nullable=False),
        sa.Column("hsn", sa.String(length=8), nullable=False),
        sa.Column("base_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("base_unit", sa.String(length=16), nullable=False),
        sa.Column("taxable", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("gst_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("cgst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("sgst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("igst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("base_qty > 0", name=op.f("ck_debit_note_line_positive_qty")),
        sa.ForeignKeyConstraint(
            ["debit_note_id"],
            ["debit_note.id"],
            name=op.f("fk_debit_note_line_debit_note_id_debit_note"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_debit_note_line_item_id_item"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_line_id"],
            ["purchase_line.id"],
            name=op.f("fk_debit_note_line_purchase_line_id_purchase_line"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_debit_note_line")),
        sa.UniqueConstraint(
            "debit_note_id", "line_no", name=op.f("uq_debit_note_line_debit_note_id_line_no")
        ),
    )
    op.create_table(
        "credit_note_line",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("credit_note_id", sa.Integer(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("sales_line_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=150), nullable=False),
        sa.Column("hsn", sa.String(length=8), nullable=False),
        sa.Column("base_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("base_unit", sa.String(length=16), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("taxable", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("gst_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("cgst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("sgst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("igst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("restocked_at", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("base_qty > 0", name=op.f("ck_credit_note_line_positive_qty")),
        sa.ForeignKeyConstraint(
            ["credit_note_id"],
            ["credit_note.id"],
            name=op.f("fk_credit_note_line_credit_note_id_credit_note"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_credit_note_line_item_id_item"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["restocked_at"],
            ["location.id"],
            name=op.f("fk_credit_note_line_restocked_at_location"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sales_line_id"],
            ["sales_line.id"],
            name=op.f("fk_credit_note_line_sales_line_id_sales_line"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_note_line")),
        sa.UniqueConstraint(
            "credit_note_id", "line_no", name=op.f("uq_credit_note_line_credit_note_id_line_no")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(op.f("ck_approval_approval_action"), "approval", type_="check")
    op.create_check_constraint(op.f("ck_approval_approval_action"), "approval", APPROVAL_OLD)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("credit_note_line")
    op.drop_table("debit_note_line")
    op.drop_index("ix_credit_note_invoice", table_name="credit_note")
    op.drop_table("credit_note")
    op.drop_index("ix_debit_note_purchase", table_name="debit_note")
    op.drop_table("debit_note")
    # ### end Alembic commands ###
