"""opening balances and ledgers

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-09 17:01:19.778135+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


APPEND_ONLY = ("stock_ledger", "party_ledger")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_ledger",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("qty_in", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("qty_out", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column(
            "ref_type",
            sa.Enum(
                "opening",
                "purchase",
                "purchase_return",
                "sale",
                "sale_return",
                "transfer",
                "adjustment",
                name="stock_ref",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("ref_id", sa.Integer(), nullable=True),
        sa.Column("narration", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "(qty_in > 0) <> (qty_out > 0)", name=op.f("ck_stock_ledger_one_direction")
        ),
        sa.CheckConstraint(
            "qty_in >= 0 AND qty_out >= 0", name=op.f("ck_stock_ledger_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["item.id"], name=op.f("fk_stock_ledger_item_id_item"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_stock_ledger_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_ledger")),
    )
    op.create_index(
        "ix_stock_ledger_item_location",
        "stock_ledger",
        ["item_id", "location_id", "entry_date"],
        unique=False,
    )
    op.create_index("ix_stock_ledger_ref", "stock_ledger", ["ref_type", "ref_id"], unique=False)
    op.create_table(
        "opening_balance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "stock",
                "receivable",
                "customer_advance",
                "payable",
                "supplier_advance",
                name="opening_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "posted",
                name="opening_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posted_by", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(kind = 'stock' AND item_id IS NOT NULL AND location_id IS NOT NULL AND quantity > 0 AND unit_cost IS NOT NULL AND party_id IS NULL AND amount IS NULL) OR (kind <> 'stock' AND party_id IS NOT NULL AND amount > 0 AND item_id IS NULL AND location_id IS NULL AND quantity IS NULL)",
            name=op.f("ck_opening_balance_shape_by_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_opening_balance_item_id_item"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_opening_balance_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party.id"],
            name=op.f("fk_opening_balance_party_id_party"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["site.id"],
            name=op.f("fk_opening_balance_site_id_site"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opening_balance")),
    )
    op.create_index(
        "uq_opening_money",
        "opening_balance",
        ["party_id", sa.literal_column("coalesce(site_id, 0)"), "kind"],
        unique=True,
        postgresql_where=sa.text("kind <> 'stock'"),
    )
    op.create_index(
        "uq_opening_stock",
        "opening_balance",
        ["item_id", "location_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'stock'"),
    )
    op.create_table(
        "party_ledger",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column(
            "account",
            sa.Enum(
                "receivable",
                "payable",
                name="ledger_account",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column(
            "ref_type",
            sa.Enum(
                "opening",
                "sale",
                "purchase",
                "payment",
                "credit_note",
                "debit_note",
                "rebate",
                "freight",
                name="party_ref",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("ref_id", sa.Integer(), nullable=True),
        sa.Column("doc_no", sa.String(length=20), nullable=True),
        sa.Column("debit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("credit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("narration", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("(debit > 0) <> (credit > 0)", name=op.f("ck_party_ledger_one_side")),
        sa.CheckConstraint("debit >= 0 AND credit >= 0", name=op.f("ck_party_ledger_non_negative")),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party.id"],
            name=op.f("fk_party_ledger_party_id_party"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["site.id"], name=op.f("fk_party_ledger_site_id_site"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_party_ledger")),
    )
    op.create_index(
        "ix_party_ledger_party", "party_ledger", ["party_id", "account", "entry_date"], unique=False
    )
    op.create_index("ix_party_ledger_ref", "party_ledger", ["ref_type", "ref_id"], unique=False)
    # ### end Alembic commands ###

    # Ledgers are append-only (ADR 0003): refuse UPDATE and DELETE below the application too.
    op.execute(
        """
        CREATE FUNCTION forbid_ledger_change() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only: % is not allowed', TG_TABLE_NAME, TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table in APPEND_ONLY:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_ledger_change()"
        )


def downgrade() -> None:
    for table in APPEND_ONLY:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS forbid_ledger_change()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_party_ledger_ref", table_name="party_ledger")
    op.drop_index("ix_party_ledger_party", table_name="party_ledger")
    op.drop_table("party_ledger")
    op.drop_index(
        "uq_opening_stock", table_name="opening_balance", postgresql_where=sa.text("kind = 'stock'")
    )
    op.drop_index(
        "uq_opening_money",
        table_name="opening_balance",
        postgresql_where=sa.text("kind <> 'stock'"),
    )
    op.drop_table("opening_balance")
    op.drop_index("ix_stock_ledger_ref", table_name="stock_ledger")
    op.drop_index("ix_stock_ledger_item_location", table_name="stock_ledger")
    op.drop_table("stock_ledger")
    # ### end Alembic commands ###
