"""rates and margins

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-09 17:22:32.279501+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_rate",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("entered_unit", sa.String(length=16), nullable=False),
        sa.Column("entered_rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.CheckConstraint("rate >= 0", name=op.f("ck_customer_rate_non_negative")),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from", name=op.f("ck_customer_rate_period_order")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_customer_rate_item_id_item"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party.id"],
            name=op.f("fk_customer_rate_party_id_party"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_rate")),
    )
    op.create_index(
        "ix_customer_rate_lookup",
        "customer_rate",
        ["party_id", "item_id", "valid_from"],
        unique=False,
    )
    op.create_table(
        "item_margin",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("margin_per_base_unit", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.CheckConstraint("margin_per_base_unit >= 0", name=op.f("ck_item_margin_non_negative")),
        sa.ForeignKeyConstraint(
            ["item_id"], ["item.id"], name=op.f("fk_item_margin_item_id_item"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_margin")),
        sa.UniqueConstraint("tenant_id", "item_id", name=op.f("uq_item_margin_tenant_id_item_id")),
    )
    op.create_table(
        "market_rate",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("entered_unit", sa.String(length=16), nullable=False),
        sa.Column("entered_rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.CheckConstraint("rate >= 0", name=op.f("ck_market_rate_non_negative")),
        sa.ForeignKeyConstraint(
            ["item_id"], ["item.id"], name=op.f("fk_market_rate_item_id_item"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_rate")),
        sa.UniqueConstraint(
            "tenant_id",
            "item_id",
            "effective_date",
            name=op.f("uq_market_rate_tenant_id_item_id_effective_date"),
        ),
    )
    op.create_index(
        "ix_market_rate_lookup", "market_rate", ["item_id", "effective_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_market_rate_lookup", table_name="market_rate")
    op.drop_table("market_rate")
    op.drop_table("item_margin")
    op.drop_index("ix_customer_rate_lookup", table_name="customer_rate")
    op.drop_table("customer_rate")
    # ### end Alembic commands ###
