"""daily closing

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-09 18:39:44.778511+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_closing",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("closing_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "closed",
                "reopened",
                name="closing_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("invoices_count", sa.Integer(), nullable=False),
        sa.Column("sales_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("returns_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("opening_cash", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cash_in", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cash_out", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("expected_cash", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("counted_cash", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("difference", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("closed_by", sa.Integer(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pdf_key", sa.String(length=200), nullable=True),
        sa.Column("reopened_by", sa.Integer(), nullable=True),
        sa.Column("reopened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reopen_reason", sa.String(length=300), nullable=True),
        sa.Column("times_closed", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_daily_closing_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_closing")),
        sa.UniqueConstraint(
            "tenant_id",
            "location_id",
            "closing_date",
            name=op.f("uq_daily_closing_tenant_id_location_id_closing_date"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("daily_closing")
    # ### end Alembic commands ###
