"""stock adjustments with reasons

Revision ID: 0016
Revises: 0015
Create Date: 2026-10-10 01:35:51.857293+00:00

FM2 (docs/FINANCE_REVIEW.md F3, F15): stock adjustment documents with a reason, a reason
column on the stock ledger, the adjustment approval limit and the ITC-on-shortages setting.
Hand edits: the duplicated enum CHECKs autogenerate writes are removed; the new stock ref,
approval action and number series widen their CHECK constraints (Alembic does not diff
those); a ledger reason is allowed only on adjustment rows; adjustments get the
issued-document triggers of migration 0014. Adding a nullable column rewrites no ledger row,
so the append-only triggers stay untouched and old rows keep a blank reason.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

STOCK_REF_OLD = (
    "ref_type IN ('opening', 'purchase', 'purchase_return', 'sale', 'sale_return', "
    "'transfer', 'adjustment')"
)
STOCK_REF_NEW = (
    "ref_type IN ('opening', 'purchase', 'purchase_return', 'sale', 'sale_return', "
    "'transfer', 'adjustment', 'stock_adjustment')"
)
APPROVAL_OLD = (
    "action IN ('credit_override', 'below_cost', 'discount', 'backdate', 'late_return', "
    "'expense')"
)
APPROVAL_NEW = (
    "action IN ('credit_override', 'below_cost', 'discount', 'backdate', 'late_return', "
    "'expense', 'stock_adjustment')"
)
DOC_TYPE_OLD = (
    "doc_type IN ('sales_invoice', 'credit_note', 'debit_note', 'delivery_challan', "
    "'purchase_entry', 'payment_receipt', 'cash_voucher')"
)
DOC_TYPE_NEW = (
    "doc_type IN ('sales_invoice', 'credit_note', 'debit_note', 'delivery_challan', "
    "'purchase_entry', 'payment_receipt', 'cash_voucher', 'stock_adjustment')"
)
ISSUED = ("stock_adjustment", "stock_adjustment_line")


def _swap_check(name: str, table: str, condition: str) -> None:
    op.drop_constraint(op.f(name), table, type_="check")
    op.create_check_constraint(op.f(name), table, condition)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_adjustment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("adjustment_date", sa.Date(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "weighbridge_gain",
                "weighbridge_loss",
                "breakage",
                "damage",
                "theft",
                "free_sample",
                "count_correction",
                name="adjustment_reason",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("approval_id", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approval.id"],
            name=op.f("fk_stock_adjustment_approval_id_approval"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_stock_adjustment_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_adjustment")),
        sa.UniqueConstraint(
            "tenant_id", "number", name=op.f("uq_stock_adjustment_tenant_id_number")
        ),
    )
    op.create_index(
        "ix_stock_adjustment_location_date",
        "stock_adjustment",
        ["location_id", "adjustment_date"],
        unique=False,
    )
    op.create_table(
        "stock_adjustment_line",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("adjustment_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "in",
                "out",
                name="stock_direction",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_adjustment_line_positive_qty")),
        sa.ForeignKeyConstraint(
            ["adjustment_id"],
            ["stock_adjustment.id"],
            name=op.f("fk_stock_adjustment_line_adjustment_id_stock_adjustment"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_stock_adjustment_line_item_id_item"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_adjustment_line")),
    )
    op.add_column(
        "shop_settings",
        sa.Column(
            "adjustment_approval_limit",
            sa.Numeric(precision=14, scale=2),
            server_default="10000.00",
            nullable=False,
        ),
    )
    op.add_column(
        "shop_settings",
        sa.Column("itc_reverse_shortages", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column(
        "stock_ledger",
        sa.Column(
            "reason",
            sa.Enum(
                "weighbridge_gain",
                "weighbridge_loss",
                "breakage",
                "damage",
                "theft",
                "free_sample",
                "count_correction",
                name="adjustment_reason",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        op.f("ck_stock_ledger_reason_on_adjustments"),
        "stock_ledger",
        "reason IS NULL OR ref_type IN ('adjustment', 'stock_adjustment')",
    )
    _swap_check("ck_stock_ledger_stock_ref", "stock_ledger", STOCK_REF_NEW)
    _swap_check("ck_approval_approval_action", "approval", APPROVAL_NEW)
    _swap_check("ck_document_sequence_doc_type", "document_sequence", DOC_TYPE_NEW)
    # Adjustments are issued documents (ADR 0010): never deleted, figures never edited.
    for table in ISSUED:
        op.execute(
            f"CREATE TRIGGER {table}_no_delete BEFORE DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_issued_delete()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_edit BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_issued_edit()"
        )


def downgrade() -> None:
    for table in ISSUED:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_edit ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_delete ON {table}")
    _swap_check("ck_document_sequence_doc_type", "document_sequence", DOC_TYPE_OLD)
    _swap_check("ck_approval_approval_action", "approval", APPROVAL_OLD)
    _swap_check("ck_stock_ledger_stock_ref", "stock_ledger", STOCK_REF_OLD)
    op.drop_constraint(
        op.f("ck_stock_ledger_reason_on_adjustments"), "stock_ledger", type_="check"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_ledger", "reason")
    op.drop_column("shop_settings", "itc_reverse_shortages")
    op.drop_column("shop_settings", "adjustment_approval_limit")
    op.drop_table("stock_adjustment_line")
    op.drop_index("ix_stock_adjustment_location_date", table_name="stock_adjustment")
    op.drop_table("stock_adjustment")
    # ### end Alembic commands ###
