"""credit, approvals and receipts

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-09 17:40:41.760773+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "credit_override",
                "below_cost",
                "discount",
                "backdate",
                name="approval_action",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("requested_by", sa.Integer(), nullable=False),
        sa.Column("approved_by", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_ref", sa.String(length=40), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["party_id"], ["party.id"], name=op.f("fk_approval_party_id_party"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval")),
    )
    op.add_column("app_user", sa.Column("pin_hash", sa.String(length=255), nullable=True))
    op.add_column("party_ledger", sa.Column("applies_to", sa.String(length=20), nullable=True))
    op.add_column(
        "sales_invoice",
        sa.Column(
            "paid_at_billing", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sales_invoice", "paid_at_billing")
    op.drop_column("party_ledger", "applies_to")
    op.drop_column("app_user", "pin_hash")
    op.drop_table("approval")
    # ### end Alembic commands ###
