"""cash book and expenses

Revision ID: 0015
Revises: 0014
Create Date: 2026-10-10 00:50:26.456692+00:00

FM1 (docs/FINANCE_REVIEW.md F1, F2): expense categories, cash-book vouchers and the expense
approval limit. Hand edits: the duplicated enum CHECKs autogenerate writes are removed (the
sa.Enum columns create their own); the new approval action and number series widen their
CHECK constraints (Alembic does not diff those); vouchers get the issued-document triggers of
migration 0014.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

DEFAULT_HEADS = [
    ("Rent", "fixed"),
    ("Salaries and wages", "fixed"),
    ("Electricity", "fixed"),
    ("Loading and unloading labour", "variable"),
    ("Vehicle, fuel and repairs", "variable"),
    ("Office, tea and stationery", "fixed"),
    ("Repairs and maintenance", "fixed"),
    ("Interest and bank charges", "interest"),
    ("Other expenses", "fixed"),
]
APPROVAL_OLD = (
    "action IN ('credit_override', 'below_cost', 'discount', 'backdate', 'late_return')"
)
APPROVAL_NEW = (
    "action IN ('credit_override', 'below_cost', 'discount', 'backdate', 'late_return', "
    "'expense')"
)
DOC_TYPE_OLD = (
    "doc_type IN ('sales_invoice', 'credit_note', 'debit_note', 'delivery_challan', "
    "'purchase_entry', 'payment_receipt')"
)
DOC_TYPE_NEW = (
    "doc_type IN ('sales_invoice', 'credit_note', 'debit_note', 'delivery_challan', "
    "'purchase_entry', 'payment_receipt', 'cash_voucher')"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expense_category",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column(
            "nature",
            sa.Enum(
                "fixed",
                "variable",
                "interest",
                name="expense_nature",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_category")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_expense_category_tenant_id_name")),
    )
    op.create_table(
        "cash_entry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "expense",
                "bank_deposit",
                "bank_withdrawal",
                "owner_drawing",
                "owner_capital",
                name="cash_entry_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum(
                "cash",
                "upi",
                "bank",
                name="payment_mode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("paid_to", sa.String(length=100), nullable=True),
        sa.Column("reference", sa.String(length=60), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("reverses_id", sa.Integer(), nullable=True),
        sa.Column("approval_id", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(kind = 'expense') = (category_id IS NOT NULL)",
            name=op.f("ck_cash_entry_category_for_expenses"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_cash_entry_positive_amount")),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approval.id"],
            name=op.f("fk_cash_entry_approval_id_approval"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["expense_category.id"],
            name=op.f("fk_cash_entry_category_id_expense_category"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_cash_entry_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reverses_id"],
            ["cash_entry.id"],
            name=op.f("fk_cash_entry_reverses_id_cash_entry"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_entry")),
        sa.UniqueConstraint("reverses_id", name=op.f("uq_cash_entry_reverses_id")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_cash_entry_tenant_id_number")),
    )
    op.create_index(
        "ix_cash_entry_location_date", "cash_entry", ["location_id", "entry_date"], unique=False
    )
    op.add_column(
        "shop_settings",
        sa.Column(
            "expense_approval_limit",
            sa.Numeric(precision=14, scale=2),
            server_default="5000.00",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
    op.drop_constraint(op.f("ck_approval_approval_action"), "approval", type_="check")
    op.create_check_constraint(op.f("ck_approval_approval_action"), "approval", APPROVAL_NEW)
    op.drop_constraint(op.f("ck_document_sequence_doc_type"), "document_sequence", type_="check")
    op.create_check_constraint(
        op.f("ck_document_sequence_doc_type"), "document_sequence", DOC_TYPE_NEW
    )
    # The usual expense heads, so an upgraded installation can book expenses at once (the
    # owner renames or retires them in Settings). Same list as services/cashbook.py.
    heads = sa.table(
        "expense_category",
        sa.column("tenant_id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("nature", sa.String),
        sa.column("is_active", sa.Boolean),
    )
    op.bulk_insert(
        heads,
        [
            {"tenant_id": 1, "name": name, "nature": nature, "is_active": True}
            for name, nature in DEFAULT_HEADS
        ],
    )
    # Vouchers are issued documents (ADR 0010): never deleted, figures never edited.
    op.execute(
        "CREATE TRIGGER cash_entry_no_delete BEFORE DELETE ON cash_entry "
        "FOR EACH ROW EXECUTE FUNCTION forbid_issued_delete()"
    )
    op.execute(
        "CREATE TRIGGER cash_entry_no_edit BEFORE UPDATE ON cash_entry "
        "FOR EACH ROW EXECUTE FUNCTION forbid_issued_edit()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS cash_entry_no_edit ON cash_entry")
    op.execute("DROP TRIGGER IF EXISTS cash_entry_no_delete ON cash_entry")
    op.drop_constraint(op.f("ck_document_sequence_doc_type"), "document_sequence", type_="check")
    op.create_check_constraint(
        op.f("ck_document_sequence_doc_type"), "document_sequence", DOC_TYPE_OLD
    )
    op.drop_constraint(op.f("ck_approval_approval_action"), "approval", type_="check")
    op.create_check_constraint(op.f("ck_approval_approval_action"), "approval", APPROVAL_OLD)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shop_settings", "expense_approval_limit")
    op.drop_index("ix_cash_entry_location_date", table_name="cash_entry")
    op.drop_table("cash_entry")
    op.drop_table("expense_category")
    # ### end Alembic commands ###
