"""sales invoices

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-09 17:30:39.823928+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_invoice",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(length=16), nullable=False),
        sa.Column("financial_year", sa.String(length=5), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("bill_to_name", sa.String(length=150), nullable=False),
        sa.Column("bill_to_address", sa.Text(), nullable=False),
        sa.Column("bill_to_gstin", sa.String(length=15), nullable=True),
        sa.Column("ship_to_name", sa.String(length=150), nullable=True),
        sa.Column("ship_to_address", sa.Text(), nullable=True),
        sa.Column("ship_to_gstin", sa.String(length=15), nullable=True),
        sa.Column("place_of_supply", sa.String(length=2), nullable=False),
        sa.Column(
            "supply_kind",
            sa.Enum(
                "intra_state",
                "inter_state",
                name="supply_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "supply_type",
            sa.Enum(
                "B2B",
                "B2C",
                name="supply_type",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("taxable_value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cgst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("sgst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("igst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("round_off", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("pending_balance_at_billing", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("vehicle_no", sa.String(length=20), nullable=True),
        sa.Column("remark", sa.String(length=300), nullable=True),
        sa.Column("idempotency_key", sa.String(length=80), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "posted",
                name="invoice_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_sales_invoice_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party.id"],
            name=op.f("fk_sales_invoice_party_id_party"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["site.id"],
            name=op.f("fk_sales_invoice_site_id_site"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_invoice")),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name=op.f("uq_sales_invoice_tenant_id_idempotency_key")
        ),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_sales_invoice_tenant_id_number")),
    )
    op.create_index("ix_sales_invoice_date", "sales_invoice", ["invoice_date"], unique=False)
    op.create_index(
        "ix_sales_invoice_party", "sales_invoice", ["party_id", "invoice_date"], unique=False
    )
    op.create_table(
        "sales_line",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=150), nullable=False),
        sa.Column("hsn", sa.String(length=8), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("base_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("base_unit", sa.String(length=16), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column(
            "rate_source",
            sa.Enum(
                "customer",
                "market",
                name="rate_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("discount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_reason", sa.String(length=200), nullable=True),
        sa.Column("taxable", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("gst_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("cgst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("sgst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("igst", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "fulfilment_source",
            sa.Enum(
                "shop",
                "godown",
                "direct",
                name="fulfilment_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_location_id", sa.Integer(), nullable=True),
        sa.Column("stock_after", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("cost_per_unit", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("base_qty > 0", name=op.f("ck_sales_line_positive_qty")),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["sales_invoice.id"],
            name=op.f("fk_sales_line_invoice_id_sales_invoice"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["item.id"], name=op.f("fk_sales_line_item_id_item"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_location_id"],
            ["location.id"],
            name=op.f("fk_sales_line_source_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_line")),
        sa.UniqueConstraint("invoice_id", "line_no", name=op.f("uq_sales_line_invoice_id_line_no")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sales_line")
    op.drop_index("ix_sales_invoice_party", table_name="sales_invoice")
    op.drop_index("ix_sales_invoice_date", table_name="sales_invoice")
    op.drop_table("sales_invoice")
    # ### end Alembic commands ###
