"""eway bills and einvoices

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-09 18:16:55.088867+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "einvoice",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("irn", sa.String(length=64), nullable=False),
        sa.Column("ack_no", sa.String(length=20), nullable=False),
        sa.Column("ack_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("signed_qr", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "generated",
                "cancelled",
                name="compliance_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=200), nullable=True),
        sa.Column("responses", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["sales_invoice.id"],
            name=op.f("fk_einvoice_invoice_id_sales_invoice"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_einvoice")),
        sa.UniqueConstraint("irn", name=op.f("uq_einvoice_irn")),
        sa.UniqueConstraint(
            "tenant_id", "invoice_id", name=op.f("uq_einvoice_tenant_id_invoice_id")
        ),
    )
    op.create_table(
        "eway_bill",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=12), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "generated",
                "cancelled",
                name="compliance_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "gsp",
                "manual",
                name="eway_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("vehicle_no", sa.String(length=20), nullable=True),
        sa.Column("from_pincode", sa.String(length=6), nullable=True),
        sa.Column("to_pincode", sa.String(length=6), nullable=True),
        sa.Column("distance_km", sa.Integer(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.String(length=200), nullable=True),
        sa.Column("responses", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["sales_invoice.id"],
            name=op.f("fk_eway_bill_invoice_id_sales_invoice"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eway_bill")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_eway_bill_tenant_id_number")),
    )
    op.create_index(
        "uq_eway_bill_live_invoice",
        "eway_bill",
        ["invoice_id"],
        unique=True,
        postgresql_where=sa.text("status = 'generated'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_eway_bill_live_invoice",
        table_name="eway_bill",
        postgresql_where=sa.text("status = 'generated'"),
    )
    op.drop_table("eway_bill")
    op.drop_table("einvoice")
    # ### end Alembic commands ###
