"""weight checks attachments and supplier schemes

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-09 18:26:52.695461+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "ref_type",
            sa.Enum(
                "purchase",
                "sales_invoice",
                "trip",
                name="attachment_ref",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("ref_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "weighbridge",
                "delivery",
                "other",
                name="attachment_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("file_name", sa.String(length=150), nullable=False),
        sa.Column("content_type", sa.String(length=60), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=200), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_attachment_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachment")),
    )
    op.create_index("ix_attachment_ref", "attachment", ["ref_type", "ref_id"], unique=False)
    op.create_table(
        "supplier_scheme",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "tmt",
                "pipe",
                "cement",
                "wire",
                "angle",
                "channel",
                "other",
                name="item_category",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("target_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "rebate_rule",
            sa.Enum(
                "percent",
                "per_unit",
                "flat",
                name="rebate_rule",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("rebate_value", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("rebate_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("rebate_booked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(item_id IS NULL) <> (category IS NULL)",
            name=op.f("ck_supplier_scheme_item_or_category"),
        ),
        sa.CheckConstraint(
            "period_end >= period_start", name=op.f("ck_supplier_scheme_period_order")
        ),
        sa.CheckConstraint("target_qty > 0", name=op.f("ck_supplier_scheme_positive_target")),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_supplier_scheme_item_id_item"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["party.id"],
            name=op.f("fk_supplier_scheme_party_id_party"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_supplier_scheme")),
    )
    op.create_index("ix_supplier_scheme_party", "supplier_scheme", ["party_id"], unique=False)
    op.add_column(
        "purchase_line",
        sa.Column(
            "weight_variance_pct",
            sa.Numeric(precision=7, scale=2),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "purchase_line",
        sa.Column("weight_flagged", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("purchase_line", sa.Column("weight_note", sa.String(length=300), nullable=True))
    op.add_column(
        "sales_line", sa.Column("slip_weight", sa.Numeric(precision=14, scale=3), nullable=True)
    )
    op.add_column(
        "sales_line",
        sa.Column(
            "weight_variance_pct",
            sa.Numeric(precision=7, scale=2),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "sales_line",
        sa.Column("weight_flagged", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("sales_line", sa.Column("weight_note", sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sales_line", "weight_note")
    op.drop_column("sales_line", "weight_flagged")
    op.drop_column("sales_line", "weight_variance_pct")
    op.drop_column("sales_line", "slip_weight")
    op.drop_column("purchase_line", "weight_note")
    op.drop_column("purchase_line", "weight_flagged")
    op.drop_column("purchase_line", "weight_variance_pct")
    op.drop_index("ix_supplier_scheme_party", table_name="supplier_scheme")
    op.drop_table("supplier_scheme")
    op.drop_index("ix_attachment_ref", table_name="attachment")
    op.drop_table("attachment")
    # ### end Alembic commands ###
