"""purchases, payments, transfers and counts

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-09 17:08:50.857974+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cost_component",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column(
            "basis",
            sa.Enum(
                "per_ton",
                "per_base_unit",
                "per_trip",
                "flat",
                name="charge_basis",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("default_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_component")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_cost_component_tenant_id_name")),
    )
    op.create_table(
        "purchase",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(length=16), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("bill_no", sa.String(length=40), nullable=False),
        sa.Column("bill_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum(
                "stock",
                "direct",
                name="purchase_mode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "posted",
                name="purchase_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("goods_value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("gst_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("charges_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("supplier_payable", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_purchase_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["party.id"],
            name=op.f("fk_purchase_supplier_id_party"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_purchase_tenant_id_number")),
        sa.UniqueConstraint(
            "tenant_id",
            "supplier_id",
            "bill_no",
            name=op.f("uq_purchase_tenant_id_supplier_id_bill_no"),
        ),
    )
    op.create_index("ix_purchase_date", "purchase", ["bill_date"], unique=False)
    op.create_table(
        "stock_count",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("count_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "posted",
                name="count_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("posted_by", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_stock_count_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_count")),
    )
    op.create_table(
        "stock_transfer",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(length=16), nullable=False),
        sa.Column("from_location_id", sa.Integer(), nullable=False),
        sa.Column("to_location_id", sa.Integer(), nullable=False),
        sa.Column("transfer_date", sa.Date(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "from_location_id <> to_location_id", name=op.f("ck_stock_transfer_different_places")
        ),
        sa.ForeignKeyConstraint(
            ["from_location_id"],
            ["location.id"],
            name=op.f("fk_stock_transfer_from_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_location_id"],
            ["location.id"],
            name=op.f("fk_stock_transfer_to_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfer")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_stock_transfer_tenant_id_number")),
    )
    op.create_table(
        "payment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(length=16), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "received",
                "paid",
                name="payment_direction",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "mode",
            sa.Enum(
                "cash",
                "upi",
                "bank",
                name="payment_mode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reference", sa.String(length=60), nullable=True),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=80), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payment_positive_amount")),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_payment_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["party_id"], ["party.id"], name=op.f("fk_payment_party_id_party"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["site.id"], name=op.f("fk_payment_site_id_site"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment")),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name=op.f("uq_payment_tenant_id_idempotency_key")
        ),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_payment_tenant_id_number")),
    )
    op.create_table(
        "purchase_line",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("purchase_id", sa.Integer(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("received_quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("billed_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("received_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("gst_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("goods_value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("gst_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("charges_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "billed_qty > 0 AND received_qty > 0", name=op.f("ck_purchase_line_positive_qty")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_purchase_line_item_id_item"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_id"],
            ["purchase.id"],
            name=op.f("fk_purchase_line_purchase_id_purchase"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_line")),
        sa.UniqueConstraint(
            "purchase_id", "line_no", name=op.f("uq_purchase_line_purchase_id_line_no")
        ),
    )
    op.create_table(
        "stock_count_line",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("count_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("system_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("counted_qty", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("variance", sa.Numeric(), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["count_id"],
            ["stock_count.id"],
            name=op.f("fk_stock_count_line_count_id_stock_count"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_stock_count_line_item_id_item"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_count_line")),
        sa.UniqueConstraint(
            "count_id", "item_id", name=op.f("uq_stock_count_line_count_id_item_id")
        ),
    )
    op.create_table(
        "stock_transfer_line",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("transfer_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_stock_transfer_line_positive_qty")),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_stock_transfer_line_item_id_item"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transfer_id"],
            ["stock_transfer.id"],
            name=op.f("fk_stock_transfer_line_transfer_id_stock_transfer"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_transfer_line")),
    )
    op.create_table(
        "purchase_cost",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("purchase_line_id", sa.Integer(), nullable=False),
        sa.Column("component_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column(
            "basis",
            sa.Enum(
                "per_ton",
                "per_base_unit",
                "per_trip",
                "flat",
                name="charge_basis",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("rate", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("on_supplier_bill", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["cost_component.id"],
            name=op.f("fk_purchase_cost_component_id_cost_component"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_line_id"],
            ["purchase_line.id"],
            name=op.f("fk_purchase_cost_purchase_line_id_purchase_line"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_cost")),
    )
    op.add_column(
        "shop_settings",
        sa.Column(
            "counter_can_enter_purchases", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shop_settings", "counter_can_enter_purchases")
    op.drop_table("purchase_cost")
    op.drop_table("stock_transfer_line")
    op.drop_table("stock_count_line")
    op.drop_table("purchase_line")
    op.drop_table("payment")
    op.drop_table("stock_transfer")
    op.drop_table("stock_count")
    op.drop_index("ix_purchase_date", table_name="purchase")
    op.drop_table("purchase")
    op.drop_table("cost_component")
    # ### end Alembic commands ###
