"""orders lots and lost sales

Revision ID: 0022
Revises: 0021
Create Date: 2026-10-10 04:04:27.593891+00:00

FM10 (docs/FINANCE_REVIEW.md F25, F26): purchase orders, goods receipts, the lots a cement sale
took, and the lost-sales log. Hand edits: the document-number types and the approval actions are
CHECK constraints that Alembic does not diff, so they are widened here (and narrowed on
downgrade); purchase lines get a CHECK that a manufacturing week comes with its year; every new
table gets the issued-document triggers of migration 0014. Adding columns to purchase and
purchase_line rewrites no row. Downgrading removes the rows that use the new document types and
the new approval action.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


revision: str = "0022"
down_revision: str | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

DOC_TYPE_OLD = (
    "doc_type IN ('sales_invoice', 'credit_note', 'debit_note', 'delivery_challan', "
    "'purchase_entry', 'payment_receipt', 'cash_voucher', 'stock_adjustment', "
    "'bad_debt_writeoff', 'stock_writedown')"
)
DOC_TYPE_NEW = (
    "doc_type IN ('sales_invoice', 'credit_note', 'debit_note', 'delivery_challan', "
    "'purchase_entry', 'payment_receipt', 'cash_voucher', 'stock_adjustment', "
    "'bad_debt_writeoff', 'stock_writedown', 'purchase_order', 'goods_receipt')"
)
APPROVAL_OLD = (
    "action IN ('credit_override', 'below_cost', 'discount', 'backdate', 'late_return', "
    "'expense', 'stock_adjustment')"
)
APPROVAL_NEW = (
    "action IN ('credit_override', 'below_cost', 'discount', 'backdate', 'late_return', "
    "'expense', 'stock_adjustment', 'po_mismatch')"
)
LOT_CHECK = (
    "(mfg_week IS NULL) = (mfg_year IS NULL) AND "
    "(mfg_week IS NULL OR mfg_week BETWEEN 1 AND 53)"
)
ISSUED = (
    "purchase_order",
    "purchase_order_line",
    "goods_receipt",
    "goods_receipt_line",
    "sales_line_lot",
    "lost_sale",
)


def _swap_check(name: str, table: str, condition: str) -> None:
    op.drop_constraint(op.f(name), table, type_="check")
    op.create_check_constraint(op.f(name), table, condition)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lost_sale",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("base_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("market_rate", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.CheckConstraint("base_qty > 0", name=op.f("ck_lost_sale_positive_qty")),
        sa.ForeignKeyConstraint(
            ["item_id"], ["item.id"], name=op.f("fk_lost_sale_item_id_item"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_lost_sale_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lost_sale")),
    )
    op.create_index(
        "ix_lost_sale_location_date", "lost_sale", ["location_id", "entry_date"], unique=False
    )
    op.create_table(
        "purchase_order",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("expected_date", sa.Date(), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_purchase_order_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["party.id"],
            name=op.f("fk_purchase_order_supplier_id_party"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_purchase_order_tenant_id_number")),
    )
    op.create_index(
        "ix_purchase_order_supplier", "purchase_order", ["supplier_id", "order_date"], unique=False
    )
    op.create_table(
        "goods_receipt",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("receipt_date", sa.Date(), nullable=False),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
            name=op.f("fk_goods_receipt_location_id_location"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["purchase_order.id"],
            name=op.f("fk_goods_receipt_order_id_purchase_order"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipt")),
        sa.UniqueConstraint("tenant_id", "number", name=op.f("uq_goods_receipt_tenant_id_number")),
    )
    op.create_index("ix_goods_receipt_order", "goods_receipt", ["order_id"], unique=False)
    op.create_table(
        "purchase_order_line",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("base_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "base_qty > 0 AND rate >= 0", name=op.f("ck_purchase_order_line_positive_qty")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_purchase_order_line_item_id_item"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["purchase_order.id"],
            name=op.f("fk_purchase_order_line_order_id_purchase_order"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order_line")),
        sa.UniqueConstraint(
            "order_id", "line_no", name=op.f("uq_purchase_order_line_order_id_line_no")
        ),
    )
    op.create_table(
        "goods_receipt_line",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("receipt_id", sa.Integer(), nullable=False),
        sa.Column("order_line_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("base_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("base_qty > 0", name=op.f("ck_goods_receipt_line_positive_qty")),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
            name=op.f("fk_goods_receipt_line_item_id_item"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["purchase_order_line.id"],
            name=op.f("fk_goods_receipt_line_order_line_id_purchase_order_line"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["goods_receipt.id"],
            name=op.f("fk_goods_receipt_line_receipt_id_goods_receipt"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipt_line")),
    )
    op.create_table(
        "sales_line_lot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sales_line_id", sa.Integer(), nullable=False),
        sa.Column("purchase_line_id", sa.Integer(), nullable=False),
        sa.Column("mfg_week", sa.Integer(), nullable=True),
        sa.Column("mfg_year", sa.Integer(), nullable=True),
        sa.Column("base_qty", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("tenant_id", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("base_qty > 0", name=op.f("ck_sales_line_lot_positive_qty")),
        sa.ForeignKeyConstraint(
            ["purchase_line_id"],
            ["purchase_line.id"],
            name=op.f("fk_sales_line_lot_purchase_line_id_purchase_line"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sales_line_id"],
            ["sales_line.id"],
            name=op.f("fk_sales_line_lot_sales_line_id_sales_line"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_line_lot")),
    )
    op.create_index("ix_sales_line_lot_line", "sales_line_lot", ["sales_line_id"], unique=False)
    op.create_index(
        "ix_sales_line_lot_purchase_line", "sales_line_lot", ["purchase_line_id"], unique=False
    )
    op.add_column("purchase", sa.Column("purchase_order_id", sa.Integer(), nullable=True))
    op.add_column("purchase", sa.Column("match_approval_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_purchase_match_approval_id_approval"),
        "purchase",
        "approval",
        ["match_approval_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_purchase_purchase_order_id_purchase_order"),
        "purchase",
        "purchase_order",
        ["purchase_order_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column("purchase_line", sa.Column("mfg_week", sa.Integer(), nullable=True))
    op.add_column("purchase_line", sa.Column("mfg_year", sa.Integer(), nullable=True))
    op.add_column(
        "shop_settings",
        sa.Column(
            "po_qty_tolerance_pct",
            sa.Numeric(precision=5, scale=2),
            server_default="1.00",
            nullable=False,
        ),
    )
    op.add_column(
        "shop_settings",
        sa.Column(
            "po_rate_tolerance_pct",
            sa.Numeric(precision=5, scale=2),
            server_default="0.50",
            nullable=False,
        ),
    )
    op.create_check_constraint(op.f("ck_purchase_line_lot_week_and_year"), "purchase_line", LOT_CHECK)
    _swap_check("ck_document_sequence_doc_type", "document_sequence", DOC_TYPE_NEW)
    _swap_check("ck_approval_approval_action", "approval", APPROVAL_NEW)
    for table in ISSUED:
        op.execute(
            f"CREATE TRIGGER {table}_no_delete BEFORE DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_issued_delete()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_edit BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION forbid_issued_edit()"
        )


def downgrade() -> None:
    for table in ISSUED:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_edit ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_delete ON {table}")
    op.execute("UPDATE purchase SET match_approval_id = NULL")
    op.execute("DELETE FROM approval WHERE action = 'po_mismatch'")
    op.execute(
        "DELETE FROM document_sequence WHERE doc_type IN ('purchase_order', 'goods_receipt')"
    )
    _swap_check("ck_approval_approval_action", "approval", APPROVAL_OLD)
    _swap_check("ck_document_sequence_doc_type", "document_sequence", DOC_TYPE_OLD)
    op.drop_constraint(op.f("ck_purchase_line_lot_week_and_year"), "purchase_line", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shop_settings", "po_rate_tolerance_pct")
    op.drop_column("shop_settings", "po_qty_tolerance_pct")
    op.drop_column("purchase_line", "mfg_year")
    op.drop_column("purchase_line", "mfg_week")
    op.drop_constraint(
        op.f("fk_purchase_purchase_order_id_purchase_order"), "purchase", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_purchase_match_approval_id_approval"), "purchase", type_="foreignkey"
    )
    op.drop_column("purchase", "match_approval_id")
    op.drop_column("purchase", "purchase_order_id")
    op.drop_index("ix_sales_line_lot_purchase_line", table_name="sales_line_lot")
    op.drop_index("ix_sales_line_lot_line", table_name="sales_line_lot")
    op.drop_table("sales_line_lot")
    op.drop_table("goods_receipt_line")
    op.drop_table("purchase_order_line")
    op.drop_index("ix_goods_receipt_order", table_name="goods_receipt")
    op.drop_table("goods_receipt")
    op.drop_index("ix_purchase_order_supplier", table_name="purchase_order")
    op.drop_table("purchase_order")
    op.drop_index("ix_lost_sale_location_date", table_name="lost_sale")
    op.drop_table("lost_sale")
    # ### end Alembic commands ###
